"""empty message

Revision ID: 2872a8ef5c97
Revises: e0d6853a05dd
Create Date: 2022-07-28 17:36:06.942797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2872a8ef5c97'
down_revision = 'e0d6853a05dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('url', sa.String(length=100), nullable=True))
    op.alter_column('ticket', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('ticket', 'url')
    # ### end Alembic commands ###
